name: Java CI

# Define when the action runs, for example, on every push to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs that should run
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    # Step 1: Checkout the code from the repository
    - uses: actions/checkout@v2

    # Step 2: Set up JDK 11 (or any version you need)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # Specify the Java version you need

    # Step 3: Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml  # Adjust to your build tool if needed

    # Step 4: Run tests
    - name: Run tests
      run: mvn test

